// Comprehensive product data aligned with user flow requirements
// Categories based on jewelry types from temp-assets

const categories = [
  { key: 'bangles', name: 'Bangles', image: '/categories/2.png', description: 'Beautiful bangles in various styles and materials' },
  { key: 'earrings', name: 'Earrings', image: '/categories/3.png', description: 'Elegant earrings for every occasion' },
  { key: 'necklaces', name: 'Necklaces', image: '/categories/4.png', description: 'Stunning necklaces to complement your style' },
  { key: 'rings', name: 'Rings', image: '/categories/1.png', description: 'Exquisite rings for special moments' },
  { key: 'chains-pendants', name: 'Chains & Pendants', image: '/categories/5.png', description: 'Delicate chains and beautiful pendants' },
  { key: 'mangalsutra', name: 'Mangalsutra', image: '/categories/6.png', description: 'Traditional mangalsutra designs' },
  { key: 'bracelets-kada', name: 'Bracelets & Kada', image: '/categories/7.png', description: 'Stylish bracelets and traditional kada' },
  { key: 'hair-accessories', name: 'Hair Accessories', image: '/categories/8.png', description: 'Beautiful hair accessories and tikka' },
  { key: 'traditional', name: 'Traditional Jewelry', image: '/categories/9.png', description: 'Classic traditional jewelry pieces' },
  { key: 'sets', name: 'Jewelry Sets', image: '/categories/10.png', description: 'Complete jewelry sets for special occasions' },
];

const products = [
  // Bangles Category
  {
    title: 'Antique Ruby Gold Bangle',
    slug: 'antique-ruby-gold-bangle',
    description: 'Exquisite antique bangle crafted with ruby and gold, perfect for traditional occasions. Features intricate design work and premium finishing.',
    price: 8500,
    images: ['/products/bangles/antique-bangle-1.webp'],
    mainImage: '/products/bangles/antique-bangle-1.webp',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['2.4', '2.6', '2.8'],
    stock: 15,
    category: 'bangles',
    categories: [{ key: 'bangles', name: 'Bangles' }],
  },
  {
    title: 'Kundan Designer Bangle',
    slug: 'kundan-designer-bangle',
    description: 'Beautiful kundan bangle with traditional design elements. Handcrafted with attention to detail.',
    price: 6500,
    images: ['/products/bangles/kundan-bangle-1.webp'],
    mainImage: '/products/bangles/kundan-bangle-1.webp',
    colors: ['#FFD700', '#FFFFFF'],
    sizes: ['2.4', '2.6', '2.8', '3.0'],
    stock: 20,
    category: 'bangles',
    categories: [{ key: 'bangles', name: 'Bangles' }],
  },
  {
    title: 'Kundan Ruby Victorian Bangle',
    slug: 'kundan-ruby-victorian-bangle',
    description: 'Elegant kundan bangle with ruby stones in Victorian style design.',
    price: 7200,
    images: ['/products/bangles/kundan-bangle-2.webp'],
    mainImage: '/products/bangles/kundan-bangle-2.webp',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['2.6', '2.8'],
    stock: 12,
    category: 'bangles',
    categories: [{ key: 'bangles', name: 'Bangles' }],
  },
  {
    title: 'Zircon White Gold Bangle',
    slug: 'zircon-white-gold-bangle',
    description: 'Modern zircon bangle with white gold finish. Perfect for contemporary styling.',
    price: 5800,
    images: ['/products/bangles/zircon-bangle-1.webp'],
    mainImage: '/products/bangles/zircon-bangle-1.webp',
    colors: ['#FFFFFF', '#C0C0C0'],
    sizes: ['2.4', '2.6', '2.8'],
    stock: 18,
    category: 'bangles',
    categories: [{ key: 'bangles', name: 'Bangles' }],
  },

  // Earrings Category
  {
    title: 'Antique Ruby Gold Earrings',
    slug: 'antique-ruby-gold-earrings',
    description: 'Classic antique earrings with ruby and gold detailing. Traditional design for special occasions.',
    price: 4500,
    images: ['/products/earrings/antique-earring-1.webp'],
    mainImage: '/products/earrings/antique-earring-1.webp',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['One Size'],
    stock: 25,
    category: 'earrings',
    categories: [{ key: 'earrings', name: 'Earrings' }],
  },
  {
    title: 'Antique Ruby Chandbali Earrings',
    slug: 'antique-ruby-chandbali-earrings',
    description: 'Beautiful chandbali style antique earrings with ruby stone work.',
    price: 4200,
    images: ['/products/earrings/antique-earring-2.webp'],
    mainImage: '/products/earrings/antique-earring-2.webp',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['One Size'],
    stock: 22,
    category: 'earrings',
    categories: [{ key: 'earrings', name: 'Earrings' }],
  },
  {
    title: '92.5 Silver Earrings',
    slug: '925-silver-earrings',
    description: 'Premium 92.5 silver earrings with contemporary design. Lightweight and comfortable.',
    price: 2800,
    images: ['/products/earrings/silver-earring-1.webp'],
    mainImage: '/products/earrings/silver-earring-1.webp',
    colors: ['#C0C0C0', '#FFFFFF'],
    sizes: ['One Size'],
    stock: 30,
    category: 'earrings',
    categories: [{ key: 'earrings', name: 'Earrings' }],
  },
  {
    title: 'Trendy Pearl Gold Earrings',
    slug: 'trendy-pearl-gold-earrings',
    description: 'Modern trendy earrings with pearl and gold combination. Perfect for daily wear.',
    price: 3200,
    images: ['/products/earrings/trendy-earring-1.webp'],
    mainImage: '/products/earrings/trendy-earring-1.webp',
    colors: ['#FFD700', '#FFFFFF'],
    sizes: ['One Size'],
    stock: 28,
    category: 'earrings',
    categories: [{ key: 'earrings', name: 'Earrings' }],
  },
  {
    title: 'Zircon White Gold Earrings',
    slug: 'zircon-white-gold-earrings',
    description: 'Elegant zircon earrings with white gold finish. Sparkling design for special events.',
    price: 3800,
    images: ['/products/earrings/zircon-earring-1.webp'],
    mainImage: '/products/earrings/zircon-earring-1.webp',
    colors: ['#FFFFFF', '#C0C0C0'],
    sizes: ['One Size'],
    stock: 20,
    category: 'earrings',
    categories: [{ key: 'earrings', name: 'Earrings' }],
  },

  // Necklaces Category
  {
    title: 'Antique Ruby Green Gold Necklace',
    slug: 'antique-ruby-green-gold-necklace',
    description: 'Magnificent antique necklace with ruby and emerald stones in gold setting. Traditional craftsmanship.',
    price: 12500,
    images: ['/products/necklaces/antique-necklace-1.jpg'],
    mainImage: '/products/necklaces/antique-necklace-1.jpg',
    colors: ['#FFD700', '#DC143C', '#50C878'],
    sizes: ['16 inch', '18 inch', '20 inch'],
    stock: 8,
    category: 'necklaces',
    categories: [{ key: 'necklaces', name: 'Necklaces' }],
  },
  {
    title: 'Kundan Victorian Necklace',
    slug: 'kundan-victorian-necklace',
    description: 'Elegant kundan necklace in Victorian style. Perfect for bridal and festive wear.',
    price: 9800,
    images: ['/products/necklaces/kundan-necklace-1.webp'],
    mainImage: '/products/necklaces/kundan-necklace-1.webp',
    colors: ['#FFD700', '#50C878'],
    sizes: ['16 inch', '18 inch'],
    stock: 10,
    category: 'necklaces',
    categories: [{ key: 'necklaces', name: 'Necklaces' }],
  },
  {
    title: '92.5 Silver Designer Necklace',
    slug: '925-silver-designer-necklace',
    description: 'Contemporary 92.5 silver necklace with modern design elements.',
    price: 6800,
    images: ['/products/necklaces/silver-necklace-1.webp'],
    mainImage: '/products/necklaces/silver-necklace-1.webp',
    colors: ['#C0C0C0'],
    sizes: ['16 inch', '18 inch', '20 inch'],
    stock: 15,
    category: 'necklaces',
    categories: [{ key: 'necklaces', name: 'Necklaces' }],
  },
  {
    title: 'Zircon Ruby Gold Necklace',
    slug: 'zircon-ruby-gold-necklace',
    description: 'Stunning zircon necklace with ruby accents in gold. Perfect for special occasions.',
    price: 8500,
    images: ['/products/necklaces/zircon-necklace-1.webp'],
    mainImage: '/products/necklaces/zircon-necklace-1.webp',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['16 inch', '18 inch'],
    stock: 12,
    category: 'necklaces',
    categories: [{ key: 'necklaces', name: 'Necklaces' }],
  },

  // Chains and Pendants
  {
    title: '92.5 Silver Chain',
    slug: '925-silver-chain',
    description: 'Premium quality 92.5 silver chain. Durable and elegant for daily wear.',
    price: 3500,
    images: ['/products/chains-pendants/silver-chain-1.webp'],
    mainImage: '/products/chains-pendants/silver-chain-1.webp',
    colors: ['#C0C0C0'],
    sizes: ['16 inch', '18 inch', '20 inch', '22 inch'],
    stock: 25,
    category: 'chains-pendants',
    categories: [{ key: 'chains-pendants', name: 'Chains & Pendants' }],
  },
  {
    title: 'Silver Pendant Earring Set',
    slug: 'silver-pendant-earring-set',
    description: 'Beautiful 92.5 silver pendant and earring set with white gold finish.',
    price: 4800,
    images: ['/products/chains-pendants/silver-pendant-set-1.webp'],
    mainImage: '/products/chains-pendants/silver-pendant-set-1.webp',
    colors: ['#C0C0C0', '#FFFFFF'],
    sizes: ['One Size'],
    stock: 18,
    category: 'chains-pendants',
    categories: [{ key: 'chains-pendants', name: 'Chains & Pendants' }],
  },
  {
    title: 'Temple Ruby Green Pendant',
    slug: 'temple-ruby-green-pendant',
    description: 'Traditional temple jewelry pendant with ruby and emerald stones in gold and silver.',
    price: 5500,
    images: ['/products/chains-pendants/temple-pendant-1.jpg'],
    mainImage: '/products/chains-pendants/temple-pendant-1.jpg',
    colors: ['#FFD700', '#C0C0C0', '#DC143C', '#50C878'],
    sizes: ['One Size'],
    stock: 12,
    category: 'chains-pendants',
    categories: [{ key: 'chains-pendants', name: 'Chains & Pendants' }],
  },

  // Rings
  {
    title: 'Kundan Ivory Pink Ring',
    slug: 'kundan-ivory-pink-ring',
    description: 'Beautiful kundan finger ring with ivory and pink stone combination.',
    price: 3200,
    images: ['/products/rings/kundan-ring-1.webp'],
    mainImage: '/products/rings/kundan-ring-1.webp',
    colors: ['#FFFFF0', '#FFC0CB'],
    sizes: ['6', '7', '8', '9', '10'],
    stock: 20,
    category: 'rings',
    categories: [{ key: 'rings', name: 'Rings' }],
  },
  {
    title: '92.5 Silver White Gold Ring',
    slug: '925-silver-white-gold-ring',
    description: '92.5 silver ring with white gold finish. Elegant and comfortable.',
    price: 2800,
    images: ['/products/rings/silver-ring-1.webp'],
    mainImage: '/products/rings/silver-ring-1.webp',
    colors: ['#C0C0C0', '#FFFFFF'],
    sizes: ['6', '7', '8', '9', '10', '11'],
    stock: 25,
    category: 'rings',
    categories: [{ key: 'rings', name: 'Rings' }],
  },
  {
    title: 'Trendy Zircon White Gold Ring',
    slug: 'trendy-zircon-white-gold-ring',
    description: 'Modern trendy ring with zircon stones in white gold finish.',
    price: 3500,
    images: ['/products/rings/trendy-ring-1.webp'],
    mainImage: '/products/rings/trendy-ring-1.webp',
    colors: ['#FFFFFF', '#C0C0C0'],
    sizes: ['6', '7', '8', '9', '10'],
    stock: 18,
    category: 'rings',
    categories: [{ key: 'rings', name: 'Rings' }],
  },

  // Mangalsutra
  {
    title: 'Antique Ruby Gold Mangalsutra',
    slug: 'antique-ruby-gold-mangalsutra',
    description: 'Traditional antique mangalsutra with ruby stones in gold. 16-inch length.',
    price: 15500,
    images: ['/products/mangalsutra/antique-mangalsutra-1.webp'],
    mainImage: '/products/mangalsutra/antique-mangalsutra-1.webp',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['16 inch'],
    stock: 8,
    category: 'mangalsutra',
    categories: [{ key: 'mangalsutra', name: 'Mangalsutra' }],
  },
  {
    title: 'Trendy White Gold Mangalsutra',
    slug: 'trendy-white-gold-mangalsutra',
    description: 'Modern trendy mangalsutra in white gold finish. Contemporary design.',
    price: 12800,
    images: ['/products/mangalsutra/trendy-mangalsutra-1.webp'],
    mainImage: '/products/mangalsutra/trendy-mangalsutra-1.webp',
    colors: ['#FFFFFF', '#C0C0C0'],
    sizes: ['16 inch', '18 inch'],
    stock: 10,
    category: 'mangalsutra',
    categories: [{ key: 'mangalsutra', name: 'Mangalsutra' }],
  },
  {
    title: 'Zircon Designer Mangalsutra',
    slug: 'zircon-designer-mangalsutra',
    description: 'Elegant zircon mangalsutra with contemporary design elements.',
    price: 11500,
    images: ['/products/mangalsutra/zircon-mangalsutra-1.webp'],
    mainImage: '/products/mangalsutra/zircon-mangalsutra-1.webp',
    colors: ['#FFFFFF', '#FFD700'],
    sizes: ['16 inch'],
    stock: 12,
    category: 'mangalsutra',
    categories: [{ key: 'mangalsutra', name: 'Mangalsutra' }],
  },

  // Bracelets and Kada
  {
    title: '92.5 Silver Bracelet',
    slug: '925-silver-bracelet',
    description: 'Premium 92.5 silver bracelet with elegant design. Comfortable daily wear.',
    price: 4200,
    images: ['/products/bracelets-kada/silver-bracelet-1.webp'],
    mainImage: '/products/bracelets-kada/silver-bracelet-1.webp',
    colors: ['#C0C0C0'],
    sizes: ['7 inch', '8 inch'],
    stock: 20,
    category: 'bracelets-kada',
    categories: [{ key: 'bracelets-kada', name: 'Bracelets & Kada' }],
  },
  {
    title: '92.5 Silver Kada',
    slug: '925-silver-kada',
    description: 'Traditional 92.5 silver kada with classic design. Perfect for men and women.',
    price: 5500,
    images: ['/products/bracelets-kada/silver-kada-1.webp'],
    mainImage: '/products/bracelets-kada/silver-kada-1.webp',
    colors: ['#C0C0C0'],
    sizes: ['2.4', '2.6', '2.8'],
    stock: 15,
    category: 'bracelets-kada',
    categories: [{ key: 'bracelets-kada', name: 'Bracelets & Kada' }],
  },

  // Hair Accessories
  {
    title: 'Antique Ruby Gold Hair Brooch',
    slug: 'antique-ruby-gold-hair-brooch',
    description: 'Exquisite antique hair brooch with ruby stones in gold. Traditional hair accessory.',
    price: 6800,
    images: ['/products/hair-accessories/antique-hair-brooch-1.jpg'],
    mainImage: '/products/hair-accessories/antique-hair-brooch-1.jpg',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['One Size'],
    stock: 10,
    category: 'hair-accessories',
    categories: [{ key: 'hair-accessories', name: 'Hair Accessories' }],
  },
  {
    title: 'Antique Ruby Gold Tikka',
    slug: 'antique-ruby-gold-tikka',
    description: 'Beautiful antique tikka with ruby stones in gold. Perfect for bridal wear.',
    price: 4500,
    images: ['/products/hair-accessories/antique-tikka-1.webp'],
    mainImage: '/products/hair-accessories/antique-tikka-1.webp',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['One Size'],
    stock: 12,
    category: 'hair-accessories',
    categories: [{ key: 'hair-accessories', name: 'Hair Accessories' }],
  },
  {
    title: 'Trendy Pearl Gold Saree Brooch',
    slug: 'trendy-pearl-gold-saree-brooch',
    description: 'Modern trendy saree brooch with pearl and gold combination.',
    price: 3200,
    images: ['/products/hair-accessories/trendy-saree-brooch-1.webp'],
    mainImage: '/products/hair-accessories/trendy-saree-brooch-1.webp',
    colors: ['#FFD700', '#FFFFFF'],
    sizes: ['One Size'],
    stock: 15,
    category: 'hair-accessories',
    categories: [{ key: 'hair-accessories', name: 'Hair Accessories' }],
  },

  // Traditional Jewelry
  {
    title: 'Antique Ruby Gold Matil',
    slug: 'antique-ruby-gold-matil',
    description: 'Traditional antique matil with ruby stones in gold. Classic temple jewelry.',
    price: 8500,
    images: ['/products/traditional/antique-matil-1.jpg'],
    mainImage: '/products/traditional/antique-matil-1.jpg',
    colors: ['#FFD700', '#DC143C'],
    sizes: ['One Size'],
    stock: 8,
    category: 'traditional',
    categories: [{ key: 'traditional', name: 'Traditional Jewelry' }],
  },
  {
    title: 'Temple Green Gold Silver Matil',
    slug: 'temple-green-gold-silver-matil',
    description: 'Traditional temple matil with green stones in gold and silver combination.',
    price: 7200,
    images: ['/products/traditional/temple-matil-1.webp'],
    mainImage: '/products/traditional/temple-matil-1.webp',
    colors: ['#FFD700', '#C0C0C0', '#50C878'],
    sizes: ['One Size'],
    stock: 10,
    category: 'traditional',
    categories: [{ key: 'traditional', name: 'Traditional Jewelry' }],
  },
];

module.exports = { categories, products };